### ISSUE TITLE
Autonuke should be disabled by default, `autonuke_time: 0` nukes at the beginning of the round

### ISSUE THREAD

**Issue by PatPeter** [KadeDev/Common-Utils#17]
These are the default configs for Common Utils. The `util_enable_autonuke` config from EXILED 1 seems to no longer exist.

I set `autonuke_time` to 0 and it **set the nuke off on round start on all of my servers**. 

```
  # The amount of time (in seconds) after the round starts, before the facilities auto-nuke will start.
  autonuke_time: 600
  # Wether or not the nuke should be unable to be disabled during the auto-nuke countdown.
  autonuke_lock: true
```

The autonuke is not part of base gameplay and there's no reason for Common Utils to _force_ every server to have an autonuke enabled. As a temporary fix I just set it to a few hours.

`autonuke_lock` should also be disabled by default. The autonuke being on by default wouldn't have been so bad if it weren't locked and impossible for players to stop after 10 minutes.

**Comment by galaxy119** [comment]
Set the time to -1 to disable it if I remember correctly.
