### ISSUE TITLE
ragdoll_cleanup_delay and item_cleanup_delay should default to 0

### ISSUE THREAD

**Issue by PatPeter** [KadeDev/Common-Utils#20]
Assuming that 0 disables ragdoll and item cleanup (and doesn't initiate a ragdoll/item cleanup instantly on round start), neither of these features should be enabled by default for an installation of Common Utilities.

If `autonuke_time` is disabled by being set to `-1`, I'm unsure whether 0 or -1 disables these configs as well. If it is -1 to disable, I will correct my issue title.

**Comment by galaxy119** [comment]
26f8bf9

**Comment by PatPeter** [comment]
Thank you very much!
