### ISSUE TITLE
util_914_roles should change roles in-place, not respawn and then teleport

### ISSUE THREAD

**Issue by PatPeter** [KadeDev/Common-Utils#8]
Here is my configuration for 914:

```
util_914_roles: ClassD-Scp0492:Rough, Scientist-Scp0492:Rough, NtfCadet-FacilityGuard:Rough, NtfLieutenant-NtfCadet:Rough, NtfCommander-NtfLieutenant:Rough, ChaosInsurgency-NtfCommander:OneToOne, NtfCommander-ChaosInsurgency:OneToOne, Scp93953-Scp93989:OneToOne, Scp93989-Scp93953:OneToOne, Scp0492-ClassD:VeryFine, FacilityGuard-NtfCadet:VeryFine, NtfCadet-NtfLieutenant:VeryFine, NtfLieutenant-NtfCommander:VeryFine
```

Right now, this is _virtually unusable_ because it wipes the inventories of all humans after upgrading them. In addition, if a Class D is converted to an SCP-049-2 and then back, he will not have his former inventory. Both of these were possible in default ServerMod2.

**Comment by galaxy119** [comment]
MP1 works very differently from MP2, and changing roles without respawning them then teleporting them back simply isn't possible right now.
As for the inventories, I'm working on that.
