### ISSUE TITLE
Customising classes HP is broken

### ISSUE THREAD

**Issue by Sky287** [KadeDev/Common-Utils#9]
Hey, I've tried customising different classes HP values, however it does not appear to be working. I am using the latest version posted from Joker (3/12/2020)

util_role_health: Scp173:3800

**Comment by PatPeter** [comment]
Do you have `util_914_items` or `util_914_roles` set? When I set either of these two configs, it breaks my customized HP for SCPs.

**Comment by Sky287** [comment]
> Do you have `util_914_items` or `util_914_roles` set? When I set either of these two configs, it breaks my customized HP for SCPs.

Currently have both set to false in my config.
